name: workflow Dispatch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      GreetingText:
        description: 'Url'
        required: true
        default: 'Hello'
      
jobs:
  setup:
    name: start-workflow
    runs-on: ubuntu-latest
    outputs:
      max_parallel_jobs: ${{ steps.setup-matrix.outputs.max_parallel_jobs }}
      matrix_jobs: ${{ steps.setup-matrix.outputs.matrix_jobs }}
    steps:
      - name: Get sources from github
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup strategy matrix
        id: setup-matrix
        uses: ./.github/actions/setup-matrix

      - name: Show Outcomes
        shell: pwsh
        run: |
          Write-Host "matrix_jobs: ${{ steps.setup-matrix.outputs.matrix_jobs }}"
          Write-Host "max_parallel_jobs: ${{ steps.setup-matrix.outputs.max_parallel_jobs }}"

  run-matrix:
    name: Run Matrix
    strategy:
      matrix: ${{ fromJSON(needs.setup.outputs.matrix_jobs) }}
      fail-fast: false
    needs: [setup]
    runs-on: ubuntu-latest
    if: github.event_name == 'repository_dispatch' # github.event_name == 'workflow_dispatch' || github.event_name == 'workflow_call' ||
    steps:
      - name: Show Inputs
        shell: pwsh
        run: |
          Write-Host "TestFilter: ${{ matrix.TestFilter }}"
          Write-Host "Company: ${{ matrix.Company }}"      