name: Upload artifact

on:
  workflow_dispatch:
    inputs:
      GreetingText:
        description: 'What do you want to say'
        required: true
        default: 'Hi, Upload artifact'

env:
  GreetingText: ${{ github.event.inputs.GreetingText || 'hi, default' }}

jobs:
  setup:
    name: start-workflow
    runs-on: ubuntu-24.04  #replacing runs-on: ubuntu-latest with runs-on: ubuntu-24.04
    steps:
    - name: Show Inputs
      shell: pwsh
      run: |
        # Input Values
        Write-Host "GreetingText: ${{ env.GreetingText }}"

    - name: Get sources from github
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Save TestFilter into json file
      shell : pwsh
      run: |
        #Save sample file
        $folderPath = "./TestOutputArtifacts/"
        
        if (-not (Test-Path $folderPath)) {
        New-Item -ItemType Directory -Path $folderPath
            Write-Host "Folder created at $folderPath"
        } else {
            Write-Host "Folder already exists at $folderPath"
        }

        $jsonObject = @{
          TestName = "sample-artifact""
          TestFilter = @{ 
            include = @("test1", "test2")
            exclude = @("test3", "test4")}
        }
        
        $TestFilterInfo = $jsonObject | ConvertTo-Json
        Write-Host $TestFilterInfo
        $TestFilterInfo | Out-File -FilePath "$folderPath/TestFilterInfo.json"    

    - name: Generate specflow report based on runned tests
      uses: ./.github/actions/upload-artifact
      with:
        TestNames: "sample-artifact"
        TestRunType: "Playwright"
        TestReportName: "test-report-name"
        OutputArtifactsName: "OutputArtifacts"
 